name: build-warnings

# Controls when the action will run.
on:
  workflow_call:

jobs:
  build-warnings:
    runs-on: ubuntu-latest
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"

    steps:

      - name: Checkout ss repo
        uses: actions/checkout@v2

      - name: Get admb and put in path
        run: |
          wget https://github.com/admb-project/admb/releases/download/admb-12.3/admb-12.3-linux.zip
          sudo unzip admb-12.3-linux.zip -d /usr/local/bin
          sudo chmod 755 /usr/local/bin/admb-12.3/bin/admb
          echo "/usr/local/bin/admb-12.3/bin" >> $GITHUB_PATH

      - name: Build stock synthesis with warnings
        run: |
          rm -rf SS330
          mkdir SS330
          /bin/bash ./Make_SS_330_new.sh -a /usr/local/bin/admb-12.3 -b SS330 -w &> warnings_ss.txt
          
      - name:  Print warnings
        run: cat warnings_ss.txt

      - name: Archive warnings text file
        if: always()
        uses: actions/upload-artifact@main
        with:
          name: 'warnings_ss.txt'
          path: warnings_ss.txt

